version: "2.1"
services:
  guacamole:
    image: guacamole/guacamole
    container_name: some-guacamole
    environment:
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=some_password
      - GUACD_HOSTNAME=some-guacd
      - GUACD_PORT=4822
      - MYSQL_HOSTNAME=some-mysql
      - MYSQL_PORT=3306
      - TZ=Europe/Paris
    ports:
      - 8080:8080
    restart: unless-stopped

  guacd:
    image: guacamole/guacd
    container_name: some-guacd
    restart: unless-stopped

  mysql:
    image: mysql
    container_name: some-mysql
    environment:
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=some_password
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      -  /home/config/guacamole:/var/lib/mysql
    restart: unless-stopped
