version: "3"
services:
  guacamole:
    image: jwetzell/guacamole
    container_name: guacamole
    volumes:
      - ./postgres:/config
    ports:
      - 8080:8080
    TOTP_ENABLED: "true"
volumes:
  postgres:
    driver: local
